export const PAIRS = [
  "AUDUSD", "AUDCAD", "AUDCHF", "AUDJPY", "EURUSD", "EURAUD", "EURCHF", "EURJPY", "EURCAD", "EURGBP",
  "GBPAUD", "GBPUSD", "GBPJPY", "GBPCAD", "GBPCHF", "USDJPY", "USDCAD", "USDCHF", "NZDJPY", "NZDUSD", "XAUUSD"
].sort();

export const STRATEGIES = [
  "ACCUMULATION MANIPULATION DISTRIBUTION (AMD - OWL)",
  "LIQUIDITY SWEEP REVERSAL (LSR - HAWK)",
  "BREAK RETEST CONTINUE (BRC - EAGLE)",
  "DYNAMIC TRENDLINE BOUNCE (DTB - OSPREY)",
  "TREND RELOAD CONTINUATION (TRC - FALCON)"
];