export const PAIRS = [
  "AUDUSD", "AUDCAD", "AUDCHF", "AUDJPY", "AUDNZD", "CADJPY", "CADCHF", "CHFJPY", "EURUSD", "EURAUD", "EURCHF", "EURJPY", "EURCAD", "EURGBP", "EURNZD", "GBPNZD",
  "GBPAUD", "GBPUSD", "GBPJPY", "GBPCAD", "GBPCHF", "NZDCAD", "NZDJPY", "NZDUSD", "NZDCHF",  "USDJPY", "USDCAD", "USDCHF", "XAUUSD"
].sort();

export const STRATEGIES = [
  "ACCUMULATION MANIPULATION DISTRIBUTION (AMD - OWL)",
  "LIQUIDITY SWEEP REVERSAL (LSR - HAWK)",
  "BREAK RETEST CONTINUE (BRC - EAGLE)",
  "DYNAMIC TRENDLINE BOUNCE (DTB - OSPREY)",
  "TREND RELOAD CONTINUATION (TRC - FALCON)",
  "HIGH SWEEP STRIKE (HSS - PEREGRINE)"
];